name: validar-readme

on:
  push:
  pull_request:

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Validar README
        run: test -f README.md
